"""Build the served crest images from the committed sources.

    uv run python -m tools.build_crests           # rebuild web/static/crests/
    uv run python -m tools.build_crests --check   # exit 1 if the build is stale

Each source in `assets/crests/` (lossless WebP, up to 640px) becomes one lossy WebP
fitted inside a SIZE-pixel box, named `<key>-<hash>.webp` so a changed image is a changed
URL (A106 -- css/js get the same treatment from `tools.stamp_assets`). The mapping from
key to file name is written to `web/crest_files.json`, which `web.crests` reads.

TEAM COLOURS ARE DERIVED FROM THE CREST, never picked by hand. Every opaque, reasonably
vivid pixel votes for its hue, weighted by saturation x brightness, so the colour a crest
is most strikingly painted in wins -- Chennai's orange lion over its larger blue lettering.
Kolkata comes out gold rather than purple by the same rule (the gold is vivid, the purple
dark); both are KKR's own colours and it was accepted as it stands. From that one hue:

    --team       the colour itself, brightness clamped so a stripe or glow reads
    --team-deep  22% of it over the site's navy -- the base a crest sits on. A crest is
                 NEVER put on its own main colour: RCB gold on gold vanished in testing.
    --team-ink   the colour lifted until it clears 4.5:1 against --team-deep, for text

written as one class per key into `web/static/crests.css`.

`--check` needs no image library: it compares each source's hash and each output's hash
against what the manifest recorded, so a source replaced without a rebuild, or an output
edited by hand, fails it. Run it before deploying, beside the other two gates.
"""

from __future__ import annotations

import colorsys
import hashlib
import io
import json
import pathlib
import sys

from web.crests import CRESTS, FILES_JSON

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = ROOT / "assets" / "crests"
OUT = ROOT / "web" / "static" / "crests"
CSS = ROOT / "web" / "static" / "crests.css"
NAVY = (6, 13, 31)           # --bg in style.css

# Fits a crest shown at up to ~160 CSS pixels on a 2x screen. The largest a crest is
# drawn anywhere is the draft's deal card; nothing needs more.
SIZE = 320
QUALITY = 86


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:10]


def _luminance(c) -> float:
    def ch(x):
        x /= 255
        return x / 12.92 if x <= .03928 else ((x + .055) / 1.055) ** 2.4
    return .2126 * ch(c[0]) + .7152 * ch(c[1]) + .0722 * ch(c[2])


def _contrast(a, b) -> float:
    hi, lo = sorted((_luminance(a), _luminance(b)), reverse=True)
    return (hi + .05) / (lo + .05)


def _with_lightness(c, lightness: float) -> tuple[int, int, int]:
    h, _, s = colorsys.rgb_to_hls(*(x / 255 for x in c))
    return tuple(round(x * 255) for x in colorsys.hls_to_rgb(h, lightness, s))


def team_colours(im) -> dict[str, str]:
    """team / deep / ink, as hex, from a crest image. See the module docstring."""
    im = im.convert("RGBA")
    im.thumbnail((160, 160))
    bins = [[0.0, 0.0, 0.0, 0.0] for _ in range(18)]      # 20-degree hue bins
    for r, g, b, a in im.get_flattened_data():
        if a < 200:
            continue
        h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
        if s < .3 or v < .2:                               # greys, black, white: no vote
            continue
        w = s * v
        bin_ = bins[int(h * 18) % 18]
        bin_[0] += w; bin_[1] += r * w; bin_[2] += g * w; bin_[3] += b * w
    w, r, g, b = max(bins, key=lambda x: x[0])
    if not w:                                             # a crest with no colour at all
        return {"team": "#8a94a8", "deep": "#1a2236", "ink": "#c3cad8"}
    hue = (r / w, g / w, b / w)
    lightness = colorsys.rgb_to_hls(*(x / 255 for x in hue))[1]
    team = _with_lightness(hue, min(max(lightness, .42), .6))
    deep = tuple(round(team[i] * .22 + NAVY[i] * .78) for i in range(3))
    ink, lightness = team, colorsys.rgb_to_hls(*(x / 255 for x in team))[1]
    while _contrast(ink, deep) < 4.5 and lightness < .92:
        lightness += .02
        ink = _with_lightness(team, lightness)
    hexed = lambda c: "#%02x%02x%02x" % c
    return {"team": hexed(team), "deep": hexed(deep), "ink": hexed(ink)}


def _css(colours: dict[str, dict[str, str]]) -> str:
    lines = ["/* GENERATED by tools.build_crests from the crest images -- do not edit. */"]
    for key in sorted(colours):
        c = colours[key]
        lines.append(f".crest-{key}{{--team:{c['team']};--team-deep:{c['deep']};"
                     f"--team-ink:{c['ink']}}}")
    return "\n".join(lines) + "\n"


def _keys() -> list[str]:
    return sorted({c.key for c in CRESTS})


def build() -> None:
    from PIL import Image  # dev-only dependency; --check never needs it

    OUT.mkdir(parents=True, exist_ok=True)
    files, sources, colours = {}, {}, {}
    for key in _keys():
        src = SOURCES / f"{key}.webp"
        raw = src.read_bytes()
        im = Image.open(io.BytesIO(raw)).convert("RGBA")
        colours[key] = team_colours(im)
        im.thumbnail((SIZE, SIZE), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, "WEBP", quality=QUALITY, method=6)
        data = buf.getvalue()
        name = f"{key}-{_sha(data)}.webp"
        (OUT / name).write_bytes(data)
        files[key], sources[key] = name, _sha(raw)
    for stale in OUT.glob("*.webp"):
        if stale.name not in files.values():
            stale.unlink()
    FILES_JSON.write_text(json.dumps({"files": files, "sources": sources,
                                      "colours": colours}, indent=2) + "\n")
    CSS.write_text(_css(colours))
    total = sum((OUT / f).stat().st_size for f in files.values())
    print(f"built {len(files)} crests, {total / 1024:.0f} kB in all")


def check() -> int:
    problems = []
    try:
        manifest = json.loads(FILES_JSON.read_text())
    except (OSError, ValueError):
        print(f"{FILES_JSON.name} missing or unreadable -- run tools.build_crests")
        return 1
    for key in _keys():
        src, name = SOURCES / f"{key}.webp", manifest["files"].get(key)
        if not src.exists():
            problems.append(f"{key}: no source at {src.relative_to(ROOT)}")
        elif manifest["sources"].get(key) != _sha(src.read_bytes()):
            problems.append(f"{key}: source changed since the last build")
        if not name or not (OUT / name).exists():
            problems.append(f"{key}: built file missing")
        elif not name.endswith(f"-{_sha((OUT / name).read_bytes())}.webp"):
            problems.append(f"{key}: {name} does not match its own content")
    if not CSS.exists() or CSS.read_text() != _css(manifest.get("colours", {})):
        problems.append(f"{CSS.name}: out of step with the manifest's colours")
    extra = {p.name for p in OUT.glob("*.webp")} - set(manifest["files"].values())
    problems += [f"{e}: not in the manifest" for e in sorted(extra)]
    for p in problems:
        print(p)
    if not problems:
        print(f"all {len(_keys())} crests current")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(check() if "--check" in sys.argv else (build() or 0))
