"""Keep the shared page shell -- nav, sign-in dialog, footer -- identical on every page.

    uv run python -m tools.shell           # write each partial into every page
    uv run python -m tools.shell --check   # exit 1 if any page is out of step

WHY. The pages are static files served from the CDN (A105), so there is no server-side
include, and rendering the nav from JavaScript would paint every page without one first.
So the markup lives in each page -- but written from ONE source, `web/partials/*.html`,
between markers:

    <!-- shell:nav -->  ...  <!-- /shell:nav -->

Before this existed every page carried its own hand-kept copy, and they had drifted: the
daily page held the sign-in dialog and the footer TWICE, with duplicate element ids.

Same treatment as `tools.stamp_assets`: a committed build artefact, regenerated by a
command, with `--check` as the deploy gate. Its order against `tools.stamp_assets` does not
matter -- the stamps hash css/js, never html -- but a partial that references a script
or stylesheet gets its stamp only when stamp_assets runs, so run that second.

`offline.html` is deliberately left out: it must render with nothing else reachable.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATIC = ROOT / "web" / "static"
PARTIALS = ROOT / "web" / "partials"
EXCLUDED = {"offline.html"}
REQUIRED = ("nav", "footer")        # every page; "auth" only where a page has the markers


def _block(name: str) -> re.Pattern:
    return re.compile(rf"(<!-- shell:{name} -->\n)(.*?)(<!-- /shell:{name} -->)", re.S)


def _pages() -> list[pathlib.Path]:
    return [p for p in sorted(STATIC.glob("*.html")) if p.name not in EXCLUDED]


def sync(check: bool = False) -> int:
    partials = {p.stem: p.read_text() for p in PARTIALS.glob("*.html")}
    problems, changed = [], []
    for page in _pages():
        text = page.read_text()
        new = text
        for name in REQUIRED:
            if not _block(name).search(text):
                problems.append(f"{page.name}: no <!-- shell:{name} --> markers")
        for name, body in partials.items():
            new = _block(name).sub(lambda m: m.group(1) + body + m.group(3), new)
        if new != text:
            if check:
                problems.append(f"{page.name}: shell out of step with web/partials")
            else:
                page.write_text(new)
                changed.append(page.name)
    for p in problems:
        print(p)
    if not check:
        print(f"shell written to {len(changed)} page(s)" if changed else "shell already current")
    elif not problems:
        print(f"shell current on all {len(_pages())} pages")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(sync(check="--check" in sys.argv))
